title: Randomness & Structure
description: Knowledge base for Life
theme: just-the-docs

url: https://sanjay-azad.github.io/home

aux_links:
  About Me: https://sanjay-azad.github.io/en


footer_content: "Copyright &copy; 2023 | Sanjay Azad"