title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://sanjay-azad.github.io

aux_links:
  About Me: https://sanjay-azad.github.io/en
